"use strict";

const assert = require("assert");
const fs = require("fs");
const path = require("path");

const html = fs.readFileSync(path.join(__dirname, "..", "index.html"), "utf8");
const runner = fs.readFileSync(path.join(__dirname, "run.sh"), "utf8");

assert.match(html, /<nav class="bottom-nav"[^>]*id="bottomNav"/, "mobile bottom navigation exists");
const registry = html.match(/var ROOM_DEFS=\[([\s\S]*?)\n  \];/);
assert.ok(registry, "canonical room registry exists");
const mobile = [...registry[1].matchAll(/\{id:"([^"]+)",label:"([^"]+)"[\s\S]*?mobile:(\d+)/g)]
  .map((m) => ({ id: m[1], label: m[2], order: Number(m[3]) })).filter((x) => x.order).sort((a, b) => a.order - b.order);
assert.deepStrictEqual(mobile.map((x) => x.label), ["Today", "Tasks", "Calendar", "More"], "mobile room order comes from ROOM_DEFS");
assert.match(html, /if\(d\.mobile===4\)h\+='<button[^']*data-bottom-capture/, "Capture is inserted between Tasks and Calendar");
assert.match(html, /@media \(max-width:560px\)[\s\S]*?\.primary-room-tabs\{display:none\}/, "desktop room tabs hide on phones");
assert.match(html, /\.bottom-nav\{[^}]*grid-template-columns:repeat\(5,1fr\)/, "mobile nav has five equal targets");
assert.match(html, /\.check\{[^}]*width:44px;height:44px/, "task completion target is 44x44");
assert.match(html, /\.task-more\{[^}]*width:44px;height:44px/, "task overflow target is 44x44");
assert.match(html, /more\.setAttribute\("aria-expanded"/, "task overflow exposes expanded state");
assert.match(html, /menu\.setAttribute\("role","menu"\)/, "task secondary actions use a named menu");
assert.match(html, /field\("Person"\)[\s\S]*?selEl\("editPerson",personOpts\(\),item\.personId\|\|""\)/, "task editor exposes a Person selector");
assert.match(html, /it\.personId=pf\(sv,"editPerson"\)\.value\|\|null/, "task editor can change or clear the Person link");
assert.match(html, /Roles & privacy/, "role settings stay inside an existing Plan & Review surface");
assert.match(html, /data-role-field="order"/, "role settings expose explicit display ordering");
assert.match(html, /Legacy remap preview/, "legacy role remap exposes a preview before apply");
assert.match(html, /Project Hub/, "Projects expose the canonical Project Hub inside the existing room");
assert.match(html, /data-project-context=/, "Project Hub exposes a copyable privacy-aware context packet");
assert.match(html, /data-restart-complete=/, "Resume Capsule exposes an explicit content-free restart completion signal");
assert.match(html, /paletteReturnFocus/, "command palette retains a focus return target");
assert.match(html, /closePalette\(false\)/, "executing a palette command yields focus to its destination");
assert.match(html, /aria-label="Council question"/, "Today Council input has an accessible name");
assert.match(html, /selEl\("editGoal"/, "task editor exposes the implemented goal link");
assert.match(html, /id="commitmentViews"/, "Tasks exposes commitment saved views inside the existing room");
assert.match(html, /summary\.textContent="Commitment, waiting & delegation"/, "commitment fields are progressively disclosed");
assert.match(html, /selEl\("editCommitment"/, "task editor exposes the bounded commitment type registry");
assert.match(html, /selEl\("editExecution"/, "task editor exposes the bounded execution state registry");
assert.match(html, /Why this needs review/, "risk reason codes have a visible explanation surface");
assert.match(html, /PROMISE_START_BY/, "start-by risk uses an explicit reason code");
assert.match(html, /WAITING_REVIEW/, "waiting review uses an explicit reason code");
assert.doesNotMatch(html, /urgencyScore|commitmentScore|weightedPriority/i, "commitment selection does not use a hidden weighted score");
assert.match(html, /id="todayRole"/, "Today exposes an explicit active-role control");
assert.match(html, /id="todayMode"/, "Today exposes an explicit day-mode control");
assert.match(html, /id="todayCapacity"/, "Today exposes an explicit capacity control");
assert.match(html, /active-day-mode/, "active day mode has a device-local side-store key");
assert.doesNotMatch(html, /state\.portfolio\.activeModeId\s*=/, "active day mode never creates a sync conflict");
assert.match(html, /ROLE_CROSSOVER_PROMISE/, "hard promises explain cross-role visibility");
assert.match(html, /Why included and deferred\?/, "Today explains both sides of its ordered rules");
assert.match(html, /data-stuck-reason=/, "Do Next Coach exposes bounded stuck reasons");
assert.match(html, /Proposal only\. No task, date, delegate, or project state changed\./, "Do Next Coach states its non-mutating consequence");
assert.match(html, /WIP Governor/, "Projects expose the WIP Governor inside the existing room");
assert.match(html, /Caps expose overload; they never pause, archive, or delete a project\./, "WIP cap changes are explicitly non-mutating");
assert.match(html, /data-portfolio-decision="ship"[\s\S]*?data-portfolio-decision="schedule"[\s\S]*?data-portfolio-decision="pause"[\s\S]*?data-portfolio-decision="kill"[\s\S]*?data-portfolio-decision="admit"[\s\S]*?data-portfolio-decision="support"/, "project governance exposes all six explicit decisions");
assert.match(html, /id="pOverrideReason"[\s\S]*?id="pOverrideReview"/, "over-cap admission requires visible reason and review controls");
assert.match(html, /Weekly Portfolio Review/, "Plan & Review contains the canonical weekly portfolio review");
assert.match(html, /data-portfolio-undo=/, "portfolio decisions expose bounded Undo");
assert.doesNotMatch(html, /state\.projects[^;]*\.status\s*=\s*["']Paused["'][^;]*projectWipLimit/, "WIP cap code does not silently pause projects");
assert.match(html, /id="buildProjectSelect"/, "new Studio missions require an explicit project choice");
assert.match(html, /Studio Incubator placeholder/, "Studio offers an explicit non-active Incubator placeholder");
assert.match(html, /data-role-remap-undo/, "role remap exposes bounded Undo");
assert.doesNotMatch(html, /\{id:"roles",label:/, "roles do not create a new top-level room");
assert.doesNotMatch(html, /Add your first one above and link tasks to it\./, "Goals does not promise task links before goalId ships");
assert.match(html, /Overdue · /, "overdue state is explicit text");
assert.match(html, /class="focus-reason"/, "NOW exposes a quiet attention reason");
assert.match(html, /<summary>Why included and deferred\?<\/summary>/, "attention rules are progressively disclosed");
assert.match(html, /data-focus-reset="1"/, "keyboard and pointer users can clear explicit focus");
assert.doesNotMatch(html, /universal urgency score|productivity score/i, "focus UI does not expose a hidden numerical score");
assert.match(html, /class="context-budget"/, "AI consent preview shows a compact record and byte budget");
assert.match(html, /<details class="ai-receipt">/, "proposal receipts are collapsed by default");
assert.match(html, /readonly/, "terminal and error proposal text cannot be silently reapplied");
assert.match(html, /data-proof-convert=/, "legacy Studio missions expose reviewed one-click proof conversion");
assert.match(html, /data-proof-attempt=/, "structured missions can append bounded attempt receipts");
assert.match(html, /id="agentRegistry"/, "Studio contains the local secret-free agent profile registry");
assert.match(html, /AI Provider Control Center · zero-dollar/, "Studio contains the provider control center without adding a room");
assert.match(html, /allowPaid=false · unknown price blocks · one sequential provider · no browser keys/, "control center states the hard zero-dollar and server-only-key policy");
assert.match(html, /I approve sending exactly this textarea and manifest/, "fabric proposal dispatch requires explicit exact-context approval");
assert.match(html, /no hidden state · no auto-apply · no fan-out/, "fabric proposal surface states its bounded transport and application behavior");
assert.match(html, /\.proof-editor \.field-row>\.field\{flex:1 1 220px;min-width:0\}/, "Control Center field rows can shrink at 320px without horizontal overflow");
assert.match(html, /\$\("aiFabricControl"\)\.addEventListener\("click",handleBuildsClick\)/, "dynamic Control Center actions are wired to Studio's bounded handler");
assert.match(html, /go\("today"\);toast\(x\.status==="review"\?"Proposal ready for review"/, "completed fabric jobs hand off visibly to the Proposal Inbox");
assert.match(html, /Decision & Assumption Ledger/, "Project Hub contains the decision ledger without a new room");
assert.match(html, /Options · id \| label \| tradeoffs/, "decision capture preserves explicit options and tradeoffs");
assert.match(html, /Communication state — Ready is not Sent/, "communication commitments keep Ready distinct from Sent");
assert.match(html, /Admin & Money/, "Tasks and Plan & Review expose the explicit Admin & Money saved view");
assert.match(html, /Search all linked records/, "Library contains local typed search across canonical records");
assert.match(html, /id="typedSearchType"[\s\S]*id="typedSearchRole"[\s\S]*id="typedSearchProject"[\s\S]*id="typedSearchPerson"/, "typed search exposes type, role, project, and person filters");
assert.match(html, /data-knowledge="playbook"[\s\S]*data-knowledge="checklist"[\s\S]*data-knowledge="decision"[\s\S]*data-knowledge="attach"/, "knowledge records expose bounded provenance-preserving conversions");
assert.match(html, /I reviewed the source, project, privacy, and exact local change/, "knowledge conversion requires explicit privacy review and confirmation");
assert.match(html, /Factual evidence & wins/, "Plan & Review contains a factual evidence timeline");
assert.match(html, /KevinOS Lab Budget/, "Plan & Review contains bounded experiment metadata and content-free counters");
assert.doesNotMatch(html, /engagementScore|evidencePoints|winStreak/i, "supporting surfaces do not add engagement scoring");
assert.doesNotMatch(html, /localStorage\.setItem\([^\n]*(GROQ|MISTRAL|COHERE|OPENROUTER|SAMBANOVA|NVIDIA).*KEY/i, "no browser provider-key persistence path exists");
assert.match(html, /Studio prepares packets and tracks state; it cannot launch terminals, agents, worktrees, pushes, deploys, or provider actions/, "Studio states its non-autonomous boundary");
assert.match(html, /selEl\("bMissionStatus"/, "mission editor exposes the closed command-queue state");
assert.match(html, /taEl\("bTargetFiles"[\s\S]*inpEl\("bWriterOwner"[\s\S]*taEl\("bWriterOverride"/, "mission editor exposes target files, writer owner, and reasoned handoff path");
assert.match(html, /data-mission-review="approve"[\s\S]*data-mission-review="rework"/, "review flow has explicit approve and rework decisions");
assert.match(html, /collaborator claim remains unverified until a separate local\/manual receipt passes/i, "claim and local proof remain visibly distinct");
assert.match(runner, /node test\/studio-command\.test\.js/, "Studio command contracts run in the complete gate");
assert.match(runner, /node test\/ai-fabric-client\.test\.js/, "AI fabric client contracts run in the complete gate");
assert.match(runner, /node test\/supporting-surfaces\.test\.js/, "supporting-surface contracts run in the complete gate");
assert.match(html, /Shipped with override/, "override language remains visibly distinct from verified");
assert.match(html, /localStatus/, "proof contract distinguishes local verification from collaborator report");
assert.match(html, /role="alertdialog"/, "rare risky actions use the shared accessible interruption contract");
assert.match(html, /class="error-summary" role="alert" aria-live="assertive"/, "validation failures are announced and summarized");
assert.match(html, /function cancelHighStakes\(\)/, "Escape has one deterministic high-stakes cancel path");
assert.match(html, /highStakesReturnSelector=highStakesFocusSelector/, "high-stakes focus survives renderer replacement through a stable return selector");
assert.match(html, /id="drillBtn"[^>]*>Test backup<\/button>/, "footer exposes a manual read-only recovery drill");
assert.match(html, /none performed/, "drill result states its read-only consequence explicitly");
assert.match(html, /RECOVERY_DRILL_MAX_BYTES=5000000/, "drill enforces a named file-size ceiling");
assert.match(html, /data-friction-open="now"/, "NOW exposes an explicit friction mark entry point");
assert.match(html, /data-friction-open="capture"/, "quick capture exposes an explicit friction mark entry point");
assert.match(html, /FRICTION_KEEP=200,FRICTION_DAYS=30,FRICTION_COMPACT_MS=43200000/, "friction pilot has named compaction and retention bounds");
assert.match(html, /data-friction-toggle=/, "pilot has an explicit local on/off control");
assert.match(html, /data-friction-clear=/, "pilot has an immediate local clear path");
assert.match(html, /captureMode="quick"/, "capture defaults to quick text");
assert.match(html, /<summary>Power syntax<\/summary>/, "capture grammar is progressively disclosed");
assert.match(html, /\.vc-mic\{display:none\}/, "floating capture control does not overlap mobile content");
assert.match(html, /@media \(pointer:coarse\)\{button,a,summary,input:not\(\[type="checkbox"\]\):not\(\[type="radio"\]\):not\(\[type="hidden"\]\),select,textarea\{min-width:44px;min-height:44px\}\}/, "coarse-pointer controls keep touch targets on tablets");
assert.match(html, /\.council-capture-row\{display:grid;grid-template-columns:minmax\(0,1fr\) auto\}/, "Plan & Review Council capture wraps without mobile overflow");
assert.match(html, /@media \(prefers-reduced-motion:reduce\)[\s\S]*?animation-duration:\.01ms !important[\s\S]*?scroll-behavior:auto !important/, "reduced-motion mode suppresses all recurring animation and smooth scrolling");

console.log("responsive UI contracts ok");
